site_name: Vincent Picard - Informatique CPGE
site_description: Page personnelle de Vincent Picard et ressources pour l'informatique en MPI
site_author: Vincent Picard

nav:
  - À propos de moi :
    - aboutme/index.md
    - Enseignement : 'aboutme/enseignement.md'
    - Parcours : 'aboutme/parcours.md'
  - MPI:
    - Cours : 'mpi/cours.md'
  - PSI* / MP: 'itc/index.md'
  #  - Généralités :
  #    - Récurrence et induction : 'general/induction.md'
  #  - Langages formels :
  #    - Langages réguliers : 'langages/regexp.md'
  #    - Théorème de Kleene : 'langages/kleene.md'
  #    - Grammaires algébriques : 'langages/grammaires.md'
  #  - Algorithmique :
  #    - Algorithmes probabilistes : 'algo/proba.md'
  #    - Couplages maximaux : 'graphes/couplages.md'
  #  - Langage C:
  #    - Tableaux : 'langc/tableaux.md'

theme:
  name: material
  features:
    - content.code.copy
    - content.code.select
    - navigation.tabs
  language: fr
  palette:
    scheme: default
    primary: blue grey
    accent: pink
  icon:
    logo: fontawesome/solid/square-binary

markdown_extensions:
  - admonition
  - pymdownx.highlight:
     anchor_linenums: true
     line_spans: __span
     pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
     generic: true
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css
  - stylesheets/definition.css
