site_name: Site de Vincent Picard
site_description: Page personnelle de Vincent Picard et ressources pour l'informatique en MPI
site_author: Vincent Picard

nav:
  - Page de test: 'test/test.md'
  - À propos de moi : 'aboutme/enseignement.md'

theme:
  name: material
  features:
    - content.code.copy
    - content.code.select
    - navigation.tabs
  language: fr
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
